### PR TITLE
Pass binary parameter data without copying

### PR DESCRIPTION
**Pull request by robx**
This is the core change of #22, ported to current master. Compared to when I first filed this, the change has been used in PostgREST and hasn't caused problems there, for whatever that's worth.

### CODE REVIEW

**Comment by phadej** [comment]
Good. This is a lot cleaner now, I can see what's the patch actually does!

Have you tried this patch (on top of the refactoring) with PostgREST already?

**Comment by robx** [comment]
No, not yet. I'll let you know when that happens.

**Comment by phadej** [comment]
@robx have you had chance to check it?

**Comment by robx** [comment]
> @robx have you had chance to check it?

Not so far, no. Just rebased the patch on top of current master.

**Comment by phadej** [comment]
I released [`postgresql-libpq`](https://hackage.haskell.org/package/postgresql-libpq-0.9.5.0) with changes so far.

I'll give it some time to propagate (e.g. enter Stackage), and if it all looks fine I'll merge this and #19 and make another release.

**Comment by phadej** [comment]
Rebased (+ rerun CI) in https://github.com/haskellari/postgresql-libpq/pull/47 and merged.

**Pull request closed without merging**
